---
title: "Meteor Analysis"
output:
  html_document:
    df_print: paged
---

```{r }
source("data_cleaning_script.R")
```

# The 10 largest meteorites in the dataset

```{r}
meteorite_landings_clean %>%
  select(name, year, mass_g) %>%
  slice_max(mass_g, n = 10)
```
# Average number of fallen and found meteorites
```{r}
meteorite_landings_clean %>%
  group_by(fall) %>%
  summarise(avg_mass = mean(mass_g))
```

# Number of meteorites per year since 2000
```{r}
meteorite_landings_clean %>%
  filter(year >= 2000) %>%
  group_by(year) %>%
  summarise(meteorite_count = n())
```

```{r}
#Make a new column called latitude_zone and recode for tropical, temperate and polar
meteorite_landings_latitude <- meteorite_landings_clean %>%
  mutate(
    latitude_zone = case_when(
      latitude == 0 & longitude == 0 ~ "NA",
      abs(latitude) <= 23.5 ~ "tropical",
      abs(latitude) >= 66.5 ~ "polar",
      abs(latitude) < 66.5 ~ "temperate"
    )
  )
```

# Total number of meteorites and average size per latitude zone
```{r}
meteorite_landings_latitude %>% 
  group_by(latitude_zone) %>%
  summarise(count = n(),
            avg_mass = mean(mass_g),
            median_mass = median(mass_g))
```


